version: '3'
services:
  selenium:
    image: selenium/standalone-chrome:4
    container_name: selenium
    ports: 
      - "4444:4444"
    shm_size: "2g"
  test:
    build: .
    container_name: test_by_selenium
    volumes:
      - ./app:/opt/app
    # entrypoint: /opt/app/start.sh
    tty: true
    depends_on:
      selenium:
        condition: service_started
